[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[terminal]

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
opacity = 0.92

[window.padding]
x = 10
y = 10

[keyboard]
